theme: jekyll-theme-minimal
title: Lasse Meinen
description: Software Engineer (MSc ETH) interested in Security, Performance Optimization, and Game Development. Experienced in the development of backend systems for national-scale apps (e.g., MeteoSwiss, Post Preview App) and passionate about building robust, user-focused software. Excels in fast-paced, interdisciplinary environments.

